# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1T2jw34TUkpxHZ9GhJRvyHhHnV0yZzcc3
"""



# prompt: do clahe with the dataset based on this definition In this study, CLAHE was employed to enhance the contrast and characteristics
# of the image by making anomalies more visible. Among the histogram equalization-based
# family, CLAHE has a more realistic look in appearance and is useful in the reduction
# of noise distortion; therefore, we examined and utilized it in our dataset, as presented
# in Figure 3. A full explanation is given below to demonstrate its effectiveness:
# • The first phase of the CLAHE scheme is the generation of image transformation by
# using the histogram bin value.
# • Following that, using a clip border, the contrast is confined to a binary value from 0
# to 1. A clip boundary is applied before the process of image segmentation.
# • A precise bin score is created to prevent the background mapping areas to grayscale.
# To obtain good mapping, a histogram clip boundary is utilized.
# • Lastly, the completed CLAHE image is generated by estimating the regions of the image, then extracting, mapping, and interpolating all pixel images to achieve optimal output.


def clahe_enhance(image_path, clip_limit=2.0, tile_grid_size=(8, 8)):
    """
    Applies Contrast Limited Adaptive Histogram Equalization (CLAHE) to an image.

    Args:
        image_path: Path to the image file.
        clip_limit: Threshold for contrast limiting.
        tile_grid_size: Size of the grid for histogram equalization.

    Returns:
        The enhanced image as a NumPy array, or None if the image cannot be loaded.
    """
    try:
        img = cv2.imread(image_path, cv2.IMREAD_GRAYSCALE)  # Read as grayscale
        if img is None:
            print(f"Error: Could not load image at {image_path}")
            return None

        clahe = cv2.createCLAHE(clipLimit=clip_limit, tileGridSize=tile_grid_size)
        enhanced_img = clahe.apply(img)
        return enhanced_img

    except Exception as e:
        print(f"An error occurred: {e}")
        return None
